### ISSUE TITLE
Include API TOKEN in command

### ISSUE THREAD

**Issue by kalarize** [Screenly/cli#103]
Hi,

Is there a way to execute commands with specific API TOKEN included in the command?
For ie. : `screenly screen list abcdefgh` (abcdefgh beeing the token)

I would like to execute commands and switch between multiple tokens (including everything in a script.sh file).

Thanks!

**Comment by sergey-borovkov** [comment]
Hi, there is an environment variable that does that.

So you can run
```API_TOKEN=xxx screenly ...```

**Comment by kalarize** [comment]
Thanks for the reply!

May I ask if we can add mutliple tokens in the variable?
As I manage multiple teams, it would be quite handy.

Thanks!

**Comment by sergey-borovkov** [comment]
That would require a lot of complications in the code - perhaps it's better to handle within your scripts?

You could always keep the list of those tokens and have a loop that executes the command for each of them.

**Comment by kalarize** [comment]
For now I did this, but could be better for me long term to be able to do commands with multiple keys:
`declare -A api_keys
api_keys["team1"]="xxxxxx"
api_keys["team2"]="yyyyyyy"

cd cli
API_TOKEN=${api_keys["team1"]} ./target/release/screenly screen list -j
API_TOKEN=${api_keys["team2"]} ./target/release/screenly screen list -j`

**Comment by sergey-borovkov** [comment]
Perhaps you could do something like this then?
```
#!/bin/bash

# Exit if no arguments or TOKENS env var is not set
if [[ $# -eq 0 || -z $TOKENS ]]; then
    echo "Usage: TOKENS=\"token1 token2 ...\" $0 <command_arg1> <command_arg2> ... <command_argN>"
    exit 1
fi

for API_TOKEN in $TOKENS; do
    API_TOKEN=$API_TOKEN /path/to/screenly/cli/target/release/screenly $@
done
```

```
TOKENS="xxxxxx yyyyyyy" ./wrapper.sh screen list -j
```

How about this? This should cover you for all commands.
