### ISSUE TITLE
Fix issues with `edge-app run`

### ISSUE THREAD

**Issue by vpetersson** [Screenly/cli#117]
# Change `generage-mock-data` 

Right now we have this:

```
$ screenly edge-app run
Error: No mock-data exist. Please run "screenly edge-app generate-mock-data" and try again.
```

As discussed, let's move `generate-mock-data` to a sub-command for `run` like this `screenly edge-app run --generate-mock-data`

# Resolve Hello World

If you do `edge-app create` and then try to run it with `edge-app run`, it's currently broken and yields the following output:

```
Greetings !

I'm . Assuming you've pinned me in the right location, I'm located in (more precisely at latitude ° and longitude °).

My Screenly ID is (which conveniently is also my hostname), and I'm running on a .
```

Let's make sure we actually get the Hello World to work.

**Comment by sergey-borovkov** [comment]
Resolved in the current master
