### ISSUE TITLE
Change how tokens are inputed

### ISSUE THREAD

**Issue by vpetersson** [Screenly/cli#12]
We currently enter tokens this way:

```bash 
$ screenly login [redacted]
Login credentials have been saved.
```

There issue with this is that by default (unless you prefix the command with a space), the token will be saved in your shell's history. This should be considered a security issue.

A better approach is to simply ask the user for this in an interactive dialogue.

**Comment by sergey-borovkov** [comment]
Fixed in https://github.com/Screenly/cli/pull/44
