### ISSUE TITLE
Fix add screen command

### ISSUE THREAD

**Issue by vpetersson** [Screenly/cli#14]
I tried adding a screen just now:

```
$ screenly screen add 2k7e-th9s
Error occurred: WrongResponseStatus(200)
```

The screen was paired properly, but got an error above.

When repeating the command I got the following:

```
$ screenly screen add 2k7eth9s
Error occurred: WrongResponseStatus(400)
```

## Action Items

- [x] Fix the status code in the API end-point (should return 201, not 200)
- [ ] Add handling for 400 response code when the screen has already been paired

**Comment by sergey-borovkov** [comment]
@vpetersson you can enter a name after the command. It takes an optional name.

**Comment by vpetersson** [comment]
Got it -- i missed that.
