### ISSUE TITLE
400 Error when promoting Edge-App from Apple Silicon Machine

### ISSUE THREAD

**Issue by cocallaw** [Screenly/cli#142]
Environment Information:
CPU - Apple M1 Pro
OS - 14.1.2 (23B92)
Terminal - Warp 
CLI Installed via Homebrew
```cli
brew info screenly-cli
==> screenly/screenly-cli/screenly-cli: stable v0.2.1
Command line interface is intended for quick interaction with Screenly through terminal.
https://github.com/Screenly/cli
/opt/homebrew/Cellar/screenly-cli/v0.2.1 (7 files, 11.9MB) *
  Built from source on 2023-12-07 at 21:57:22
From: https://github.com/screenly/homebrew-screenly-cli/blob/HEAD/Formula/screenly-cli.rb
License: MIT
==> Dependencies
Build: rust ✔
```
When promoting an Edge-App using the command `screenly edge-app version promote --latest` or  `screenly edge-app version promote --revision=X` the CLI returns `Response: Ok("") Failed to promote edge app version: unknown error: 400.` All other commands leading up to the promotion step successfully complete without issue.

![Screenshot 2023-12-12 at 10 13 59 AM](https://github.com/Screenly/cli/assets/11371083/c1c0df9c-2b37-4b16-82a7-4995f69a3c43)

This behavior has been reproduced using the Weather and Power BI sample Edge Apps that are located in the [Screenly/Playground](https://github.com/Screenly/Playground) repository. 

Working directory copied from the Mac to a Windows 11 machine and was able to successfully promote both Edge-Apps using the CLI.

Was able to reproduce the issue, from different locations, using different networks/ISP providers to rule out possible network traffic filtering.

**Comment by vpetersson** [comment]
Thanks for raising this @cocallaw. @korvyashka can you please investigate this tomorrow?

**Comment by cocallaw** [comment]
Updated now showing 0.2.3 and testing.
```bash
brew info screenly-cli
==> screenly/screenly-cli/screenly-cli: stable v0.2.3
Command line interface is intended for quick interaction with Screenly through terminal.
https://github.com/Screenly/cli
/opt/homebrew/Cellar/screenly-cli/v0.2.3 (7 files, 11.9MB) *
  Built from source on 2023-12-13 at 07:30:11
From: https://github.com/screenly/homebrew-screenly-cli/blob/HEAD/Formula/screenly-cli.rb
License: MIT
==> Dependencies
Build: rust ✔
```

**Comment by cocallaw** [comment]
@vpetersson I am able to successfully promote Edge-Apps using v0.2.3 of the CLI

```bash
screenly edge-app version promote --latest
Edge app version successfully promoted.
```

**Comment by vpetersson** [comment]
Awesome. Let me know if you need anything else. 

It was a bit of a boo-boo on our end where we had to break the backward compatibility of an API endpoint.
