### ISSUE TITLE
Fix JSON output

### ISSUE THREAD

**Issue by vpetersson** [Screenly/cli#20]
It appears as some of our parsing is wrong.

```bash
$ screenly asset list --json  | jq
parse error: Invalid numeric literal at line 1, column 14
```
Looking closer into this, the error comes from the following debug message:

```bash
$ screenly asset list --json | head -n 1
2022-12-09T15:07:14.949Z INFO  [screenly] [
```

**Comment by sergey-borovkov** [comment]
Ok, it's because of today's change. Renat asked to use rust's logging library. It prepends this output.

**Comment by vpetersson** [comment]
Ok, it breaks the `-json` feature so we need to improve how we log then.
