### ISSUE TITLE
Create Brew Formula

### ISSUE THREAD

**Issue by vpetersson** [Screenly/cli#23]
[Brew](https://brew.sh/) is the most popular package manager for macOS. 

Because we expect most/many of the users of the Screenly CLI to use macOS, it makes sense to create a package for our CLI.

## References

* [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook)

**Comment by sergey-borovkov** [comment]
Done in https://github.com/Screenly/homebrew-screenly-cli
